### PR TITLE
Use Rails preview interceptors + move CI to GH Actions

### PR DESCRIPTION
**Pull request by djfpaagman**
in https://github.com/markets/maily/pull/43 support was added for inline attachments via code similar to the Rails [`ActionMailer::InlinePreviewInterceptor`](https://api.rubyonrails.org/classes/ActionMailer/InlinePreviewInterceptor.html).

ActionMailer also supports other gems to register preview interceptors, see https://api.rubyonrails.org/classes/ActionMailer/Previews/ClassMethods.html.

I ran into this when using the [premailer-rails](https://github.com/fphilipe/premailer-rails) gem, which inlines all css. For it to work with preview tools it registers an interceptor here:

https://github.com/fphilipe/premailer-rails/blob/2870060f9740de1c3f7a1da0acfc7b88e3181077/lib/premailer/rails.rb#L24-L26

----

This PR adds support for Rails preview interceptors in Maily. 

I also removed the inline attachment code, because that is included in Rails by default and by applying all preview interceptors that gets applied as well (see docs for `ActionMailer::InlinePreviewInterceptor`), as you can also see the tests of the inline attachments still pass.

I'm not sure what the next steps would be. Let me know if this PR needs work, happy to improve it and get it in a mergable state.

### CODE REVIEW

**Comment by markets** [comment]
Hi @djfpaagman and thanks a lot for contributing here!

To be honest, I've never used the `premailer` gem (neither interceptors) along with `maily`, so not sure what kind of problems you're facing. So, at that point, I'm not sure what should be the next steps 🤔. A priori, if I understood it well, these changes will keep the "inline attachments" to work as it is in master, plus, new integrations (premailer) are possible? If so, I'd be +1 to merge this one. We need to take into account compatible Rails versions:

https://github.com/markets/maily/blob/17f0cc27854ca69f571da9c797fc4f93df6e9ddb/.travis.yml#L9-L11

Maybe that's the cause of all those CI failures?

**Comment by djfpaagman** [comment]
@markets thanks for responding!

The problem with the `premailer` gem is that it without applying the interceptors the email will be unstyled, as it inlines the css for you. It's one example of a gem that I ran into that uses the interceptor approach to change stuff in emails, but i'm sure there are others as well (github search for `register_preview_interceptor` is a bit useless though). 

Yes this would keep the inline attachments working, as that's the one interceptor that Rails ships by default. Your assumptions in that regard are correct.

I'll have a look at the other Rails versions, I've only used it on 6.1 so far but I don't think it should be a big issue to solve. I'm on holiday for a bit the coming weeks, so I might get back to it a bit later.

**Comment by marian13** [comment]
@markets @djfpaagman Hi, guys.

Thank you very for all the hard work you do to build such a great gem as [maily](https://github.com/markets/maily).

I am also using a combination of the [premailer-rails](https://github.com/fphilipe/premailer-rails) and [maily](https://github.com/markets/maily) gems in my Rails 6.1 application and I am experiencing similar problems as @djfpaagman described. 

I am just curious, do you have any plans to continue working on this PR?

Thanks in advance.

**Comment by markets** [comment]
We'll probably first need to move to GH Actions, as I don't have more OSS credits in Travis. And we need to be sure the CI is passing in all available combinations. If someone wants to help with that, it would be much much appreciated :)

**Comment by djfpaagman** [comment]
@marian13: yes i'm still planning on working on it, haven't taken the time yet though. If you want you can use this monkey patch to get it working while this feature is not out yet:

```ruby
module Maily
  class Email
    # Monkey patch to support interceptors, which are used by premailer to inline all css. The preview_interceptors
    # are a feature used in the default Rails mail previewer, but Maily does not support those.
    def call
      *args = arguments && arguments.map { |arg| arg.respond_to?(:call) ? arg.call : arg }

      message = if args == [nil]
                  parameterized_mailer_klass.public_send(name)
                else
                  parameterized_mailer_klass.public_send(name, *args)
                end

      ActionMailer::Base.preview_interceptors.each do |interceptor|
        interceptor.previewing_email(message)
      end

      message
    end
  end
end
```

**Comment by djfpaagman** [comment]
@markets I finally found some time to check what was failing the build, it seems there is some flaky-ness introduced by changing the arguments for this test:
https://github.com/markets/maily/blob/3196fa380411fc2a03510e3339887f4e2b250bd6/spec/email_spec.rb#L93-L95

I fixed it by resetting it after, instead of a rewrite of the test to be more idempotent.

I also set up a Github CI flow based on [this setup from jbuilder](https://github.com/rails/jbuilder/pull/509). Let me know what you think!

**Comment by markets** [comment]
wow @djfpaagman good job! 👏🏼  thanks for the CI migration! 🙏🏼  

I'll take a deeper look this weekend but looking good 👌🏼  Just a question, why do we need those `experimental: false` inside the `exclude:` scope if that seems the default value?

**Comment by djfpaagman** [comment]
>  Just a question, why do we need those experimental: false inside the exclude: scope if that seems the default value?

I think you're right and they are not needed, it's left over from copying the config from the jbuilder gem. I've pushed a new version of the config and it still seems to test correctly. 

Side thought: maybe we can add more ruby versions to the testing matrix, as officially these are the [supported ruby/rails combinations](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions):

> 1.2 Ruby Versions
Rails generally stays close to the latest released Ruby version when it's released:
>
> Rails 7 requires Ruby 2.7.0 or newer.
Rails 6 requires Ruby 2.5.0 or newer.
Rails 5 requires Ruby 2.2.2 or newer.

**Comment by markets** [comment]
@djfpaagman v2.1.0 pushed to RubyGems:
- https://rubygems.org/gems/maily/versions/2.1.0
- https://github.com/markets/maily/blob/master/CHANGELOG.md#210
- https://github.com/markets/maily/compare/v2.0.2...v2.1.0

Thanks!! 🚀

**Pull request merged**
